#!/usr/bin/python3
import Adafruit_DHT
import numpy
import os
import time
from datetime import datetime
import json
import socket
import paho.mqtt.client as paho
import configparser

debug = False

config = configparser.ConfigParser()
config.read(os.path.basename(__file__) + ".ini")
mqttHostname = config["config"]["mqttHostname"]
mqttUsername = config["config"]["mqttUsername"]
mqttPassword = config["config"]["mqttPassword"]
deviceFriendlyNamePrefix = config["config"]["deviceFriendlyNamePrefix"]

# Define constants
# Sensor type (Adafruit_DHT.DHT11 or Adafruit_DHT.DHT22)
DHT_SENSOR = Adafruit_DHT.DHT22

# Configure GPIO pins
DHT22_PIN = 4

# how often in seconds sensor should be read
readInterval = 5

# how often in seconds data should be published
publishInterval = 60

deviceFriendlyName = deviceFriendlyNamePrefix + " RPi DHT22"

hostname = socket.gethostname()
deviceID = hostname+"-dht"

mqttTopicPrefix = hostname+"/dht"

availabilityTopic = mqttTopicPrefix + "/availability"
valuesTopic = mqttTopicPrefix + "/sensor"

haTopicPrefix = "homeassistant/sensor"

deviceAvailable = "Online"
deviceNotAvailable = "Offline"

mqttClient = None
mqttClientID = deviceID

def debugPrint(o):
    if debug:
        print(o)


# callbacks
def onConnect(client, userdata, flags, rc):
    debugPrint("onConnect")
    publishAvailability(availability=deviceAvailable)
    publishDeviceHaConfig(sensorValueName="Temperature", sensorClass="temperature", sensorUnit="°C")
    publishDeviceHaConfig(sensorValueName="Humidity", sensorClass="humidity", sensorUnit="%")

def onDisconnect(client, userdata, rc):
    pass

def onPublish(client, userdata, mid):
    debugPrint("onPublish")


def connect():
    global mqttClient

    mqttClient = paho.Client(mqttClientID)
    mqttClient.on_connect = onConnect
    mqttClient.on_disconnect = onDisconnect
    mqttClient.on_publish = onPublish
    mqttClient.username_pw_set(username=mqttUsername, password=mqttPassword)
    mqttClient.will_set(topic=availabilityTopic, payload=deviceNotAvailable, retain=True)
    mqttClient.reconnect_delay_set()

    mqttClient.connect(host=mqttHostname)
    mqttClient.loop_start()



def publish (topic, payload=None, qos=0, retain=False):
    global mqttClient

    if (type(payload) is dict):
        convertedPayload = json.dumps(payload)
    else:
        convertedPayload = payload

    result = mqttClient.publish(topic=topic, payload=convertedPayload, qos=qos, retain=retain)

    debugPrint(topic)
    if (qos != 0):
        debugPrint("qos: %d" % qos)
    if (retain):
        debugPrint("retain: True")
    if(payload):
        # print(json.dumps(payload,indent=4))
        debugPrint(convertedPayload)
    else:
        debugPrint('---DELETE---')


# Home Assistant discovery config for sensor
# {
#     "unique_id": "hostname-dht-Humidity",
#     "name": "Friendly Name Humidity",
#     "state_topic": "hostname/dht/sensor",
#     "availability_topic": "hostname/dht/availability",
#     "payload_available": "Online",
#     "payload_not_available": "Offline",
#     "force_update": true,
#     "value_template": "{{value_json['Analog']['Humidity']}}",
#     "device": {
#         "identifiers": [
#             "hostname-dht"
#         ],
#         "name": "Friendly Name RPi DHT22",
#         "model": "HomeAssistant Discovery for DHT22 on RPi",
#         "manufacturer": "Dan"
#     },
#     "device_class": "humidity",
#     "unit_of_measurement": "%"
# }

def deviceConfig():
    return {
        "identifiers":[
            deviceID
        ],
        "name": deviceFriendlyName,
        "model": "HomeAssistant Discovery for DHT22 on RPi",
        "manufacturer": "Dan"
    }

def publishDeviceHaConfig(sensorValueName,sensorClass,sensorUnit):
    uniqueID = deviceID + "-" + sensorValueName

    haConfigTopic = haTopicPrefix + "/" + uniqueID + "/config"

    configPayload = {
        "unique_id": uniqueID,
        "name": deviceFriendlyNamePrefix + " " + sensorValueName,
        "state_topic": valuesTopic,
        "availability_topic": availabilityTopic,
        "payload_available": deviceAvailable,
        "payload_not_available": deviceNotAvailable,
        "force_update": True,
        "value_template": "{{value_json['Analog']['" + sensorValueName + "']}}",
        "device": deviceConfig()
    }

    if (sensorClass):
        configPayload["device_class"] = sensorClass

    if (sensorUnit):
        configPayload["unit_of_measurement"] = sensorUnit
    
    publish(topic=haConfigTopic, payload=configPayload, retain=True)

def unpublishDeviceHaConfig(sensorValueName,sensorClass,sensorUnit):
    uniqueID = deviceID + "-" + sensorValueName
    haConfigTopic = haTopicPrefix + "/" + uniqueID + "/config"
    publish(topic=haConfigTopic, payload="")

def publishAvailability(availability):
    publish(topic=availabilityTopic,payload=deviceAvailable,retain=True)

def unpublishAvailability(availability):
    publish(topic=availabilityTopic,payload="",retain=True)


# Sensor values message
# {
#     "Time": "2022-11-18T18:01:56",
#     "Analog": {
#         "Temperature": 19.8,
#         "Humidity": 33.1
#     }
# }
def publishSensor(sensorData):
    publishTime = datetime.now().isoformat(timespec="seconds")

    temperature = betterAverage(sensorData["temperatureList"])
    humidity = betterAverage(sensorData["humidityList"])

    payload = {
        "Time": publishTime,
        "Reads": sensorData["reads"],
        "Analog": {
            "Temperature": round(temperature,1),
            "Humidity": round(humidity,1)
        }
    }

    publish(topic=valuesTopic,payload=payload)

def betterAverage(data):
    data.sort()
    q1, q3 = numpy.percentile(data, [25, 75])
    iqr = q3 - q1
    lowerBound = q1 - iqr*1.5
    upperBound = q3 + iqr*1.5
    outliersRemoved = []
    for i in data:
        if (i>=lowerBound and i<=upperBound):
            outliersRemoved.append(i)
    average = sum(outliersRemoved)/len(outliersRemoved)
    return average

def clearSensorData():
    return {
        "reads": 0,
        "temperatureList": [],
        "humidityList": []
    }

connect()
debugPrint("after connect()")

lastPublishTime = 0
lastReadTime = 0
sensorData = clearSensorData()
while (True):
    currentTime = datetime.now().timestamp()

    if (currentTime - lastReadTime >= readInterval):
        debugPrint("# Read Interval #")
        humidity, temperature = Adafruit_DHT.read_retry(DHT_SENSOR, DHT22_PIN)
        
        sensorData["reads"] += 1
        if (humidity):
            sensorData["humidityList"].append(humidity)
        if (temperature):
            sensorData["temperatureList"].append(temperature)

        lastReadTime = currentTime

    if (currentTime - lastPublishTime >= publishInterval):
        debugPrint("# Update Interval #")
        publishSensor(sensorData)

        sensorData = clearSensorData()
        lastPublishTime = currentTime

    time.sleep(1)
